# Generated by Django 5.2 on 2025-04-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands_we_work_with',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cretor_invitation_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title_1', models.TextField(blank=True, null=True)),
                ('main_title_2', models.TextField(blank=True, null=True)),
                ('highlighted_title', models.CharField(blank=True, max_length=200, null=True)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('text_2', models.TextField(blank=True, null=True)),
                ('text_3', models.TextField(blank=True, null=True)),
                ('text_4', models.TextField(blank=True, null=True)),
                ('affirmative_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='How_it_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
                ('text_title_3', models.TextField(blank=True, null=True)),
                ('subtitle_text', models.TextField(blank=True, null=True)),
                ('sub_title_1', models.TextField(blank=True, null=True)),
                ('sb1_text_1', models.TextField(blank=True, null=True)),
                ('sb1_text_2', models.TextField(blank=True, null=True)),
                ('sb1_text_3', models.TextField(blank=True, null=True)),
                ('sb1_text_4', models.TextField(blank=True, null=True)),
                ('sb1_text_5', models.TextField(blank=True, null=True)),
                ('sb1_text_6', models.TextField(blank=True, null=True)),
                ('listing_1', models.TextField(blank=True, null=True)),
                ('listing_1_text', models.TextField(blank=True, null=True)),
                ('listing_2', models.TextField(blank=True, null=True)),
                ('listing_2_text', models.TextField(blank=True, null=True)),
                ('sub_title_2', models.TextField(blank=True, null=True)),
                ('sb2_text_1', models.TextField(blank=True, null=True)),
                ('sb2_text_2', models.TextField(blank=True, null=True)),
                ('sb2_text_3', models.TextField(blank=True, null=True)),
                ('detail_text_1', models.TextField(blank=True, null=True)),
                ('dt_1', models.TextField(blank=True, null=True)),
                ('dt_1_text', models.TextField(blank=True, null=True)),
                ('dt_2', models.TextField(blank=True, null=True)),
                ('dt_2_text', models.TextField(blank=True, null=True)),
                ('dt_3', models.TextField(blank=True, null=True)),
                ('dt_3_text', models.TextField(blank=True, null=True)),
                ('closing_text', models.TextField(blank=True, null=True)),
                ('sub_title_3', models.TextField(blank=True, null=True)),
                ('sb3_text_1', models.TextField(blank=True, null=True)),
                ('sub_title_4', models.TextField(blank=True, null=True)),
                ('sb4_text_1', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms_and_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Why_jadoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
                ('text_title_3', models.TextField(blank=True, null=True)),
                ('text_title_4', models.TextField(blank=True, null=True)),
                ('text_title_5', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_bi_bi', models.TextField(blank=True, null=True)),
                ('brands', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brands_we_work_with')),
            ],
        ),
    ]
