# Generated by Django 5.2 on 2025-04-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb1_text_3',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb1_text_4',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb1_text_5',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb1_text_6',
        ),
    ]
