# Generated by Django 5.2 on 2025-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_how_it_works_sb1_text_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='business_proposition_modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
                ('card_title_1', models.TextField(blank=True, null=True)),
                ('basic_price', models.CharField(blank=True, max_length=20, null=True)),
                ('promise_1', models.TextField(blank=True, null=True)),
                ('promise_2', models.TextField(blank=True, null=True)),
                ('promise_3', models.TextField(blank=True, null=True)),
                ('notification_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='creator_proposition_modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
                ('card_title_1', models.TextField(blank=True, null=True)),
                ('promise_1', models.TextField(blank=True, null=True)),
                ('promise_2', models.TextField(blank=True, null=True)),
                ('card_title_2', models.TextField(blank=True, null=True)),
                ('promise_3', models.TextField(blank=True, null=True)),
                ('card_title_3', models.TextField(blank=True, null=True)),
                ('promise_4', models.TextField(blank=True, null=True)),
                ('card_title_4', models.TextField(blank=True, null=True)),
                ('promise_5', models.TextField(blank=True, null=True)),
                ('promise_6', models.TextField(blank=True, null=True)),
                ('notification_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cretor_proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='refund_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title_1', models.TextField(blank=True, null=True)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('text_title_2', models.TextField(blank=True, null=True)),
                ('text_2', models.TextField(blank=True, null=True)),
                ('text_title_3', models.TextField(blank=True, null=True)),
                ('text_3', models.TextField(blank=True, null=True)),
                ('text_title_4', models.TextField(blank=True, null=True)),
                ('text_4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='cretor_invitation_card',
            new_name='business_proposition',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='closing_text',
            new_name='title_1',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='detail_text_1',
            new_name='title_1_text',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='dt_1',
            new_name='title_2',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='dt_1_text',
            new_name='title_2_text',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='dt_2',
            new_name='title_3',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='dt_2_text',
            new_name='title_3_text',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='dt_3',
            new_name='title_4',
        ),
        migrations.RenameField(
            model_name='how_it_works',
            old_name='dt_3_text',
            new_name='title_4_text',
        ),
        migrations.RenameField(
            model_name='privacy_policy',
            old_name='text',
            new_name='text_1',
        ),
        migrations.RenameField(
            model_name='terms_and_conditions',
            old_name='text',
            new_name='text_1',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='listing_1',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='listing_1_text',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='listing_2',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='listing_2_text',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb1_text_1',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb1_text_2',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb2_text_1',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb2_text_2',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb2_text_3',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb3_text_1',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sb4_text_1',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sub_title_1',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sub_title_2',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sub_title_3',
        ),
        migrations.RemoveField(
            model_name='how_it_works',
            name='sub_title_4',
        ),
        migrations.AddField(
            model_name='privacy_policy',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy_policy',
            name='text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy_policy',
            name='text_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy_policy',
            name='text_title_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy_policy',
            name='text_title_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy_policy',
            name='text_title_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_and_conditions',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_and_conditions',
            name='text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_and_conditions',
            name='text_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_and_conditions',
            name='text_title_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_and_conditions',
            name='text_title_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_and_conditions',
            name='text_title_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
