# Generated by Django 5.2 on 2025-04-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('robots', models.CharField(default='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1', max_length=255)),
                ('dc_title', models.CharField(max_length=255)),
                ('dc_description', models.TextField()),
                ('dc_creator', models.CharField(max_length=255)),
                ('dc_publisher', models.CharField(max_length=255)),
                ('dc_subject', models.TextField()),
                ('dc_type', models.CharField(default='website', max_length=100)),
                ('dc_format', models.CharField(default='text/html', max_length=100)),
                ('dc_language', models.CharField(default='en-US', max_length=20)),
                ('dc_rights', models.CharField(default='Copyright © 2025 Jadoo. All rights reserved.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Meta Tag',
                'verbose_name_plural': 'SEO Meta Tags',
            },
        ),
    ]
