# Generated by Django 5.2 on 2025-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometatag',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_format',
            field=models.CharField(blank=True, default='text/html', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_language',
            field=models.CharField(blank=True, default='en-US', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_rights',
            field=models.CharField(blank=True, default='Copyright © 2025 Jadoo. All rights reserved.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='dc_type',
            field=models.CharField(blank=True, default='website', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='robots',
            field=models.CharField(blank=True, default='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seometatag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
