# Generated by Django 5.2 on 2025-05-09 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='platform_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hero')),
            ],
        ),
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='brands',
        ),
        migrations.DeleteModel(
            name='business_proposition',
        ),
        migrations.DeleteModel(
            name='business_proposition_modal',
        ),
        migrations.DeleteModel(
            name='creator_proposition_modal',
        ),
        migrations.DeleteModel(
            name='cretor_proposition',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='How_it_works',
        ),
        migrations.DeleteModel(
            name='Privacy_policy',
        ),
        migrations.DeleteModel(
            name='refund_policy',
        ),
        migrations.DeleteModel(
            name='SEOMetaTag',
        ),
        migrations.DeleteModel(
            name='Terms_and_conditions',
        ),
        migrations.DeleteModel(
            name='Why_jadoo',
        ),
        migrations.AddField(
            model_name='detail',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.platform_detail'),
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Brands_we_work_with',
        ),
    ]
