# Generated by Django 5.2 on 2025-07-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
